### ISSUE TITLE
Narrow to current file

### ISSUE THREAD

**Issue by lazy** [mohkale/consult-eglot#10]
It would be great to narrow list to symbols defined in file for current buffer.

Another solution that would work for me - reorder candidates by distance from current file. (First from current file, then from the same directory, then from parent etc, then from the rest of the project)

**Comment by mohkale** [comment]
I don't really see the need for this, isn't that what you can do with imenu already?

**Comment by lazy** [comment]
It's a shame but I didn't know that eglot integrates with imenu. Thanks.
