### ISSUE TITLE
nothing happens when invoked

### ISSUE THREAD

**Issue by gdanov** [mohkale/consult-eglot#12]
when I `M-x consult-eglot-symbols` nothing happens. No minibuffer prompt, no error (I've toggled debug on error).

installed via `use-package`, emacs 28, eglot, typescript-lsp. Did some basic debugging, everything seems right. `consult--read` is invoked, but does absolutely nothing.

edit: after disabling helm-mode I get the prompt. Obviously something interferes..

**Comment by mohkale** [comment]
@gdanov 

If you look in the consult README [it mentions](https://github.com/minad/consult/#bug-reports) helm is an unsupported UI for consult. Perhaps try one of the alternative UIs like vertico.

Closing as not an issue with consult-eglot.
