### ISSUE TITLE
invoking consult-eglot-symbols results in: "Symbol’s function definition is void: consult--position-marker"

### ISSUE THREAD

**Issue by ville-h** [mohkale/consult-eglot#13]
Invoking `consult-eglot-symbols` results in: "Symbol’s function definition is void: consult--position-marker". This is a rather recent behaviour change. It used to work with out any error messages appearing. I've updated packages of "everything" and I am using emacs 28.

Not sure if this is `constult-eglot` problem or `consult` problem, but only time I notice it is when  using `consult-eglot-symbols`. Quick grep through `consult-eglot` sources seems like it's referencing [consult--position-marker](https://github.com/mohkale/consult-eglot/blob/master/consult-eglot.el#L180), but I can't find corresponding function in either repo.

**Comment by mohkale** [comment]
@ville-h 

Looks like consult [renamed](https://github.com/minad/consult/commit/c21302c03881aeb940343c7fec4fcb819d5fc381) this function from `consult--marker` to `consult--marker-from-line-column` 4 days ago. I'll update the function in this repo.

**Comment by mohkale** [comment]
Should be fixed now. Please reopen this issue if the error persists.
