### ISSUE TITLE
invoking consult-eglot-symbols results in: "consult-eglot--transformer: Wrong number of arguments: #<subr consult--format-file-line-match>, 2"

### ISSUE THREAD

**Issue by ville-h** [mohkale/consult-eglot#14]
Invoking consult-eglot-symbols results in: "consult-eglot--transformer: Wrong number of arguments: #<subr consult--format-file-line-match>, 2"

**Comment by mohkale** [comment]
@ville-h 

Please run `M-x toggle-debug-on-error` and share the backtrace from this error condition. Please also share your consult and consult-eglot package version (or git-commit).

**Comment by ville-h** [comment]
versions:
  consult-eglot                  20230204.1550  installed             A consulting-read interface for eglot
  consult                        20230211.1204  dependency            Consulting completing-read

backtrace:

> Debugger entered--Lisp error: (wrong-number-of-arguments #<subr consult--format-file-line-match> 2)
  consult--format-file-line-match("/usr/include/bits/types/FILE.h" 7)
  consult-eglot--transformer((:containerName "" :kind 5 :location (:range (:end (:character 28 :line 6) :start (:character 24 :line 6)) :uri "file:///usr/include/bits/types/FILE.h") :name "FILE" :score 1.100000023841858))
  mapcar(consult-eglot--transformer ((:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/types/F...") :name "FILE" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/alloca.h") :name "alloca" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "basename" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "basename" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/types/c...") :name "clock_t" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "explicit_bzero" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/unistd_...") :name "gettid" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/stdint-...") :name "int16_t" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/stdint-...") :name "int32_t" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/stdint-...") :name "int64_t" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/stdint-...") :name "int8_t" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/types/l...") :name "locale_t" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/unistd.h") :name "lseek" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memccpy" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memcmp" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memcpy" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memfrob" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memmem" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memmove" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "mempcpy" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memrchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memrchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memset" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/unistd.h") :name "pathconf" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "rawmemchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "rawmemchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/unistd.h") :name "sethostname" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "sigabbrev_np" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "sigdescr_np" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/lib/clang/15.0.7/inc...") :name "size_t" :score 1.100000023841858) ...))
  #f(compiled-function (action-var65) #<bytecode 0x10116fa7ff26b71f>)(((:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/types/F...") :name "FILE" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/alloca.h") :name "alloca" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "basename" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "basename" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/types/c...") :name "clock_t" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "explicit_bzero" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/unistd_...") :name "gettid" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/stdint-...") :name "int16_t" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/stdint-...") :name "int32_t" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/stdint-...") :name "int64_t" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/stdint-...") :name "int8_t" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/types/l...") :name "locale_t" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/unistd.h") :name "lseek" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memccpy" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memcmp" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memcpy" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memfrob" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memmem" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memmove" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "mempcpy" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memrchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memrchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memset" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/unistd.h") :name "pathconf" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "rawmemchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "rawmemchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/unistd.h") :name "sethostname" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "sigabbrev_np" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "sigdescr_np" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/lib/clang/15.0.7/inc...") :name "size_t" :score 1.100000023841858) ...))
  #f(compiled-function (resp) #<bytecode 0xbd68a59ea2e1404>)([(:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/types/F...") :name "FILE" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/alloca.h") :name "alloca" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "basename" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "basename" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/types/c...") :name "clock_t" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "explicit_bzero" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/unistd_...") :name "gettid" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/stdint-...") :name "int16_t" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/stdint-...") :name "int32_t" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/stdint-...") :name "int64_t" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/stdint-...") :name "int8_t" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/include/bits/types/l...") :name "locale_t" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/unistd.h") :name "lseek" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memccpy" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memcmp" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memcpy" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memfrob" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memmem" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memmove" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "mempcpy" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memrchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memrchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "memset" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/unistd.h") :name "pathconf" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "rawmemchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "rawmemchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/unistd.h") :name "sethostname" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "sigabbrev_np" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range (:end ... :start ...) :uri "file:///usr/include/string.h") :name "sigdescr_np" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range (:end ... :start ...) :uri "file:///usr/lib/clang/15.0.7/inc...") :name "size_t" :score 1.100000023841858) ...])
  jsonrpc-connection-receive(#<eglot-lsp-server eglot-lsp-server-156af1da2420> (:id 884 :jsonrpc "2.0" :result [(:containerName "" :kind 5 :location (:range ... :uri "file:///usr/include/bits/types/F...") :name "FILE" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/alloca.h") :name "alloca" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/string.h") :name "basename" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/string.h") :name "basename" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range ... :uri "file:///usr/include/bits/types/c...") :name "clock_t" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/string.h") :name "explicit_bzero" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/bits/unistd_...") :name "gettid" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range ... :uri "file:///usr/include/bits/stdint-...") :name "int16_t" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range ... :uri "file:///usr/include/bits/stdint-...") :name "int32_t" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range ... :uri "file:///usr/include/bits/stdint-...") :name "int64_t" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range ... :uri "file:///usr/include/bits/stdint-...") :name "int8_t" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range ... :uri "file:///usr/include/bits/types/l...") :name "locale_t" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/unistd.h") :name "lseek" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/string.h") :name "memccpy" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/string.h") :name "memchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/string.h") :name "memchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/string.h") :name "memcmp" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/string.h") :name "memcpy" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/string.h") :name "memfrob" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/string.h") :name "memmem" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/string.h") :name "memmove" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/string.h") :name "mempcpy" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/string.h") :name "memrchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/string.h") :name "memrchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/string.h") :name "memset" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/unistd.h") :name "pathconf" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/string.h") :name "rawmemchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/string.h") :name "rawmemchr" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/unistd.h") :name "sethostname" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/string.h") :name "sigabbrev_np" :score 1.100000023841858) (:containerName "" :kind 12 :location (:range ... :uri "file:///usr/include/string.h") :name "sigdescr_np" :score 1.100000023841858) (:containerName "" :kind 5 :location (:range ... :uri "file:///usr/lib/clang/15.0.7/inc...") :name "size_t" :score 1.100000023841858) ...]))
  jsonrpc--process-filter(#<process EGLOT (garbage_00/(c++-mode))> "Content-Length: 21530\15\n\15\n{\"id\":884,\"jsonrpc\":\"2.0\"...")
  #<subr completing-read-default>("LSP Symbols: " #f(compiled-function (str pred action) #<bytecode -0x4c32ab1816247c9>) nil t "#" t nil nil)
  vertico-multiform--advice(#<subr completing-read-default> "LSP Symbols: " #f(compiled-function (str pred action) #<bytecode -0x4c32ab1816247c9>) nil t "#" t nil nil)
  apply(vertico-multiform--advice (#<subr completing-read-default> "LSP Symbols: " #f(compiled-function (str pred action) #<bytecode -0x4c32ab1816247c9>) nil t "#" t nil nil))
  vertico--advice(#<subr completing-read-default> "LSP Symbols: " #f(compiled-function (str pred action) #<bytecode -0x4c32ab1816247c9>) nil t "#" t nil nil)
  apply(vertico--advice #<subr completing-read-default> ("LSP Symbols: " #f(compiled-function (str pred action) #<bytecode -0x4c32ab1816247c9>) nil t "#" t nil nil))
  completing-read-default("LSP Symbols: " #f(compiled-function (str pred action) #<bytecode -0x4c32ab1816247c9>) nil t "#" t nil nil)
  completing-read("LSP Symbols: " #f(compiled-function (str pred action) #<bytecode -0x4c32ab1816247c9>) nil t "#" t nil nil)
  #f(compiled-function () #<bytecode 0xcdcffca8cd0cfd3>)()
  consult--with-preview-1(any #f(compiled-function (action cand) #<bytecode 0x1da1a3c5351cbfe0>) #f(compiled-function (narrow input cand) #<bytecode 0x7ee0abc84585115>) #f(compiled-function (&rest args2) #<bytecode 0x17df1922f17d9a87>) #f(compiled-function () #<bytecode 0xcdcffca8cd0cfd3>))
  consult--read-1(#f(compiled-function (action) #<bytecode -0xe1838c3dfe2c86e>) :history t :require-match t :prompt "LSP Symbols: " :initial "#" :category consult-lsp-symbols :lookup consult--lookup-candidate :group #f(compiled-function (cand transform) #<bytecode -0x10e04f3af490b7fa>) :narrow (:predicate #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_110> :keys ((99 . "Class") (102 . "Function") (101 . "Enum") (105 . "Interface") (109 . "Module") (110 . "Namespace") (112 . "Package") (115 . "Struct") (116 . "Type Parameter") (118 . "Variable") (65 . "Array") (66 . "Boolean") (67 . "Constant") (69 . "Enum Member") (70 . "Field") (77 . "Method") (78 . "Number") (79 . "Object") (80 . "Property") (83 . "String") (111 . "Other"))) :state #f(compiled-function (action cand) #<bytecode 0x1da1a3c5351cbfe0>) :prompt "Select: " :preview-key any :sort t :lookup #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_159>)
  consult--read(#f(compiled-function (action) #<bytecode -0xe1838c3dfe2c86e>) :history t :require-match t :prompt "LSP Symbols: " :initial "#" :category consult-lsp-symbols :lookup consult--lookup-candidate :group #f(compiled-function (cand transform) #<bytecode -0x10e04f3af490b7fa>) :narrow (:predicate #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_110> :keys ((99 . "Class") (102 . "Function") (101 . "Enum") (105 . "Interface") (109 . "Module") (110 . "Namespace") (112 . "Package") (115 . "Struct") (116 . "Type Parameter") (118 . "Variable") (65 . "Array") (66 . "Boolean") (67 . "Constant") (69 . "Enum Member") (70 . "Field") (77 . "Method") (78 . "Number") (79 . "Object") (80 . "Property") (83 . "String") (111 . "Other"))) :state #f(compiled-function (action cand) #<bytecode 0x1da1a3c5351cbfe0>))
  consult-eglot-symbols()
  funcall-interactively(consult-eglot-symbols)
  command-execute(consult-eglot-symbols)

**Comment by mohkale** [comment]
@ville-h 

Yep. This looks to be a change in consult itself that's impacting this package. I've just pushed a commit that should've fixed it. If the issue still persists please reopen this issue.
