### ISSUE TITLE
consult-lsp-symbols incompatible with embark

### ISSUE THREAD

**Issue by ewollesen** [mohkale/consult-eglot#16]
Thanks for writing consult-eglot! I use it daily and I'm super grateful for it.

I believe I've found an incompatibility in consult-eglot's integration with embark. Unfortunately, my understanding of Emacs lisp is limited, so I'll apologize in advance for not being able to better describe the problem, or how I've fixed it. With that out of the way...

### What I Was Trying To Do

Use consult-eglot-symbols, then select a candidate via embark's default action to jump to the selected symbol.

### What Happened

I was taken to a newly-created buffer, named "t".

### What I expected to Happen

I expected to be taken to the location specified for the selected symbol.

### How to Reproduce

It's not super simple to reproduce, but here's one way it could be done:

1. install Go (links provided if it's helpful)
1. install gopls (the Go LSP server)
1. start Emacs with the provided init.el file
1. open the provided main.go file
1. `M-x consult-eglot-symbols third C-. <return>`

    *"C-." is the key bound to embark-act in init.el.*

At this point, you should find yourself visiting an empty buffer called simply "t".

### Proposed Fix

My proposed fix is in the init.el file included in this bug report, and the accompanying PR. It can be tested with the following steps:

1. in the provided init.el file, uncomment the config found in the embark-consult use-package call (line 27 or so)
1. restart Emacs (or simply re-evaluate the embark-consult use-package form)
1. repeat the steps from How to Reproduce

Now you should see the expected result of being in main.go:9:5, pointing at the function called "thirdFunction".

### How the Fix Works (I Think?)

The output of consult--grep-position, while accepted by consult, is in some way incompatible with what embark expects. I'm not sure why it would expect something different, but... It seems to be. My Emacs-lisp skills are lacking to really dig into what exactly the differences are. It's possible this exposes a partial incompatibility between embark and consult, but since the fix I came up with was small and I think reasonably straight-forward, I decided to submit it here.

### Extra Discussion

You might be thinking, "isn't using the default action of embark the same as simply selecting the result from consult-eglot-symbols directly? And you'd be right, but my ultimate goal wasn't to use the default action, it's just a minimal case that shows the problem. I was trying to use embark to open the result in another window, [using a technique detailed on the embark wiki](https://github.com/oantolin/embark/wiki/Additional-Actions#run-the-default-action-in-another-window).

I did later learn that I could work around the issue with something like this:

```
C-x 4 4 C-c / third <return> ;; C-c / is my personal keybind for consult-eglot-symbols
```

But it's awfully convenient to be able to decide to open something in a new window after the fact, and embark is great for that.

### init.el

This is as small as I could get it. Unfortunately, there are a number of packages at play here, so overall it's not simple to reproduce.

```elisp
(package-initialize)

;; needed for consult-eglot package
(push '("melpa" . "https://melpa.org/packages/") package-archives)
(package-refresh-contents)

(use-package eglot
:ensure t)

(use-package embark
:ensure t
:bind (("C-." . embark-act))) ;; NOTICE this keybind is used in the "steps to reproduce"

(use-package consult
:ensure t)

(use-package project
:config
;; needed for Go integration with the built-in project package
(add-hook 'project-find-functions #'project-find-go-module))

(use-package embark-consult
:ensure t
:config
(require 'embark-consult)
;; NOTICE Uncomment this to test the suggested fix
(setf (alist-get 'consult-lsp-symbols embark-default-action-overrides)
	#'alt/embark-consult-goto-grep)
:after (embark consult))

(use-package consult-eglot
:ensure t
:after (eglot consult)
:bind (("C-c /" . consult-eglot-symbols))) ;; optional keybind

;;
;; Basic go config, as that's what I'm testing with, but any set of
;; packages that use eglot and have LSP symbol support should work
;; I imagine.
;;
;; References:
;;  Go installation: https://go.dev/doc/install
;;  gopls (Go LSP server) installation: https://github.com/golang/tools/tree/master/gopls#installation
;;  Configuring eglot & gopls: https://github.com/golang/tools/blob/master/gopls/doc/emacs.md#configuring-eglot
;;
(use-package go-mode
:ensure t
:after eglot
:hook ((go-mode . eglot-ensure)))

;; needed for Go integration with the built-in project package
(defun project-find-go-module (dir)
(when-let ((root (locate-dominating-file dir "go.mod")))
(cons 'go-module root)))

;; needed for Go integration with the built-in project package
(cl-defmethod project-root ((project (head go-module)))
(cdr project))


(custom-set-variables
;; custom-set-variables was added by Custom.
;; If you edit it by hand, you could mess it up, so be careful.
;; Your init file should contain only one such instance.
;; If there is more than one, they won't work right.
'(package-selected-packages
'(markdown-mode go-mode consult-eglot embark-consult)))
(custom-set-faces
;; custom-set-faces was added by Custom.
;; If you edit it by hand, you could mess it up, so be careful.
;; Your init file should contain only one such instance.
;; If there is more than one, they won't work right.
)

(defun alt/consult--grep-position (location)
"An alternative for use with consult-eglot-symbols

The location received when called via embark's default action is
different from that produced when called via
consult-eglot-symbols directly. This function is able to handle
input from either source to generate a compatible marker."

(let ((symbol-info (get-text-property 0 'consult--candidate location)))
;; TODO I suspect there's a better let form that can deconstruct symbol-info
(let* ((grep-params (consult-eglot--symbol-information-to-grep-params symbol-info))
	   (file (car grep-params))
	   (line (car (cdr grep-params)))
	   (col (car (cdr (cdr grep-params)))))
(consult--marker-from-line-column (funcall #'find-file file) line (or col 0)))))

(defun alt/embark-consult-goto-grep (location)
"Go to LOCATION, which should be a string with a grep match.

This is a cut and paste of embark-consult-goto-grep replacing
consult--grep-position with an alternative version.

This function shouldn't be included in the PR, as it's only
useful for injecting the alternative consult--grep-position
function thereby allowing the fix to be tested."

(consult--jump (alt/consult--grep-position location))
(pulse-momentary-highlight-one-line (point)))

```

### main.go

As I mentioned before, this should be testable with any source file that has eglot symbol support.

```go
package main

import "fmt"

func someFunction() {
	  fmt.Println("this is just some function for testing consult-eglot-symbols")
}

func thirdFunction() {
	  fmt.Println("give more choice in the jumping")
}

func main() {
	  fmt.Println("this is a test function for using consult-eglot-symbols")
}
```

**Comment by mohkale** [comment]
Wow, this is probably the most in depth bug report I've ever seen for an Emacs package. Kudos :partying_face:.

> What Happened
> I was taken to a newly-created buffer, named "t".

This is an annoying bug, I've never run into it as I don't really use embark-act as much as I should but I can understand what you're seeing.

I've adapted your PR into a new commit, when you get a chance could you try out HEAD and see if it works?

**Comment by ewollesen** [comment]
> Wow, this is probably the most in depth bug report I've ever seen for an Emacs package. Kudos 🥳.

Thanks. I'm not super well-versed in Emacs lisp, so I took my time and learned a few things. Plus I wanted to make sure I wasn't just misconfiguring something. :)

> I've adapted your PR into a new commit, when you get a chance could you try out HEAD and see if it works?

It works great, thanks. Your commit looks much better than my ham-fisted attempt, too.

Thanks again!

**Comment by mohkale** [comment]
Thanks for confirming the fix. I'll close out this ticket.
