### ISSUE TITLE
Symbol's function definition is void: eglot-server-capable

### ISSUE THREAD

**Issue by xuchengpeng** [mohkale/consult-eglot#19]
`(define-obsolete-function-alias 'eglot--server-capable 'eglot-server-capable "1.16")`

**Comment by mohkale** [comment]
This is annoying, cask will always install the most recent version of a dependency instead of the one the package requires list states. I can't test this in CI :/. But I have pushed something I think fixes it. Could you give it a go and let me know if it's no longer failing now?

**Comment by ville-h** [comment]
Appears to have fixed it for me at least.
