### ISSUE TITLE
Installation with `straight-use-package` fails if `git-lfs` is not installed

### ISSUE THREAD

**Issue by meain** [mohkale/consult-eglot#3]
Just wanted to let you know that the installation with `straight.el` will fail for anyone who does not have `git-lfs` installed.

For the images, the pattern that I have seen usually is to host it another branch or just have it in an issue and link to the url GIthub provides in the issue.

**Comment by mohkale** [comment]
Yep. I can reproduce.

Well this is a pickle :sweat:. If I rebase and remove the image files then it'll break everyones existing installations when they try to re-clone or update. If I leave it as is users will not be able to install it until they install git-lfs. 

I'll try removing the image and see whether it still fails even when the image isn't being checked out. I'll also have to be careful using git-lfs in the future. This is a deal-breaker :cry:.

**Comment by mohkale** [comment]
Uploading image here so I can link to it.

![demo](https://user-images.githubusercontent.com/23294780/131529081-7b6ad89a-98c8-40f2-9ef8-184856f8e9ef.png)

**Comment by mohkale** [comment]
@meain

Please try again now. It should work without issue.

**Comment by meain** [comment]
Looks like it is all good now. Thanks. ;)
